name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-09d7b624-bc5f-4fc5-93b
  REGION: us-east1
  REPOSITORY: my-app-repo
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
